"""empty message

Revision ID: 93229ad44601
Revises: 
Create Date: 2023-10-28 15:35:24.979879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93229ad44601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('services',
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.Time(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_services',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('services_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['services_type'], ['services.type'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'services_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments_services')
    op.drop_table('appointments')
    op.drop_table('dogs')
    op.drop_table('services')
    op.drop_table('clients')
    # ### end Alembic commands ###
